OURPAPER_DATASET_FOLDER = 'datasets/'  # <- Changing this is not supported

PREDEFINED_COCO_PATHS = {
    "coco_2017_train": ("coco/train2017", "coco/annotations/instances_train2017.json"),
    "coco_2017_val": ("coco/val2017", "coco/annotations/instances_val2017.json"),
    "coco_2017_test": ("coco/test2017", "coco/annotations/image_info_test2017.json"),
    "coco_2017_test-dev": ("coco/test2017", "coco/annotations/image_info_test-dev2017.json"),
    "coco_2017_val_100": ("coco/val2017", "coco/annotations/instances_val2017_100.json"),
}

# Obtained by parsing COCO2017
COCO_ID_CAT_MAPPING = {1: 'person',
                       2: 'bicycle',
                       3: 'car',
                       4: 'motorcycle',
                       5: 'airplane',
                       6: 'bus',
                       7: 'train',
                       8: 'truck',
                       9: 'boat',
                       10: 'traffic light',
                       11: 'fire hydrant',
                       13: 'stop sign',
                       14: 'parking meter',
                       15: 'bench',
                       16: 'bird',
                       17: 'cat',
                       18: 'dog',
                       19: 'horse',
                       20: 'sheep',
                       21: 'cow',
                       22: 'elephant',
                       23: 'bear',
                       24: 'zebra',
                       25: 'giraffe',
                       27: 'backpack',
                       28: 'umbrella',
                       31: 'handbag',
                       32: 'tie',
                       33: 'suitcase',
                       34: 'frisbee',
                       35: 'skis',
                       36: 'snowboard',
                       37: 'sports ball',
                       38: 'kite',
                       39: 'baseball bat',
                       40: 'baseball glove',
                       41: 'skateboard',
                       42: 'surfboard',
                       43: 'tennis racket',
                       44: 'bottle',
                       46: 'wine glass',
                       47: 'cup',
                       48: 'fork',
                       49: 'knife',
                       50: 'spoon',
                       51: 'bowl',
                       52: 'banana',
                       53: 'apple',
                       54: 'sandwich',
                       55: 'orange',
                       56: 'broccoli',
                       57: 'carrot',
                       58: 'hot dog',
                       59: 'pizza',
                       60: 'donut',
                       61: 'cake',
                       62: 'chair',
                       63: 'couch',
                       64: 'potted plant',
                       65: 'bed',
                       67: 'dining table',
                       70: 'toilet',
                       72: 'tv',
                       73: 'laptop',
                       74: 'mouse',
                       75: 'remote',
                       76: 'keyboard',
                       77: 'cell phone',
                       78: 'microwave',
                       79: 'oven',
                       80: 'toaster',
                       81: 'sink',
                       82: 'refrigerator',
                       84: 'book',
                       85: 'clock',
                       86: 'vase',
                       87: 'scissors',
                       88: 'teddy bear',
                       89: 'hair drier',
                       90: 'toothbrush'}

COCO_ALL_CLASSES_NUMBER = len(COCO_ID_CAT_MAPPING)
COCO_CAT_ID_MAPPING = {v: k for k, v in COCO_ID_CAT_MAPPING.items()}
COCO_MAX_NOVEL_SPLIT = 4
COCO_CLASSES_PER_SPLIT =  COCO_ALL_CLASSES_NUMBER // COCO_MAX_NOVEL_SPLIT

# PASCAL VOC categories
PASCAL_VOC_ALL_CATEGORIES = {
    1: ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair',
        'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep',
        'train', 'tvmonitor', 'bird', 'bus', 'cow', 'motorbike', 'sofa'],
    2: ['bicycle', 'bird', 'boat', 'bus', 'car', 'cat', 'chair', 'diningtable',
        'dog', 'motorbike', 'person', 'pottedplant', 'sheep', 'train',
        'tvmonitor', 'aeroplane', 'bottle', 'cow', 'horse', 'sofa'],
    3: ['aeroplane', 'bicycle', 'bird', 'bottle', 'bus', 'car', 'chair', 'cow',
        'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'train',
        'tvmonitor', 'boat', 'cat', 'motorbike', 'sheep', 'sofa'],
}

PASCAL_VOC_NOVEL_CATEGORIES = {
    1: ['bird', 'bus', 'cow', 'motorbike', 'sofa'],
    2: ['aeroplane', 'bottle', 'cow', 'horse', 'sofa'],
    3: ['boat', 'cat', 'motorbike', 'sheep', 'sofa'],
}

PASCAL_VOC_BASE_CATEGORIES = {
    1: ['aeroplane', 'bicycle', 'boat', 'bottle', 'car', 'cat', 'chair',
        'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'sheep',
        'train', 'tvmonitor'],
    2: ['bicycle', 'bird', 'boat', 'bus', 'car', 'cat', 'chair', 'diningtable',
        'dog', 'motorbike', 'person', 'pottedplant', 'sheep', 'train',
        'tvmonitor'],
    3: ['aeroplane', 'bicycle', 'bird', 'bottle', 'bus', 'car', 'chair', 'cow',
        'diningtable', 'dog', 'horse', 'person', 'pottedplant', 'train',
        'tvmonitor'],
}
